### ISSUE TITLE
文件配置理解

### ISSUE THREAD

**Issue by yangtzelsl** [shiguanghuxian/seaweedfs-docker#1]
请问docker-compose.yml文件中的master1，master2，master3怎么理解？
1.是否需要多master配置？
2.master1,2,3是不太主机的主机名还是特定表达？（因为发现volume需要制定ip，而master直接使用域名）
如上，不太理解，期待回复，谢谢

**Comment by shiguanghuxian** [comment]
就是一个名字，可以忽略这个名字，这个很久之前的版本了，你用的时候建议根据新版本取用
推荐另一文件存储服务 [https://github.com/minio/minio](https://github.com/minio/minio)
